#!/bin/sh
TYPE="${BLOCK_INSTANCE:-mem}"

awk -v type=$TYPE '
/^MemAvailable:/ {
	available_mem=$2
}
/^SwapFree:/ {
	swap_free=$2
}
END {
	# full text
	if (type == "swap")
		printf("%.1fG\n", swap_free/1024/1024)
	else
		printf("%.1fG\n", available_mem/1024/1024)

	# TODO: short text

	# TODO: color (if less than X%)
}
' /proc/meminfo
